spring.application.name=camel-quarkus

#camel.springboot.main-run-controller=true
# Habilita el levantamiento automático de Artemis en modo test
quarkus.artemis.devservices.enabled=true

spring.artemis.url=tcp://localhost:61616
spring.artemis.user=artemis
spring.artemis.password=artemis

jao.queue.input.name=mensaje-input
jao.queue.output.name=mensaje-output
